export const ContactErrorCodes = {
  NAME_REQUIRED: "NAME_REQUIRED",
  NAME_INVALID_TYPE: "NAME_INVALID_TYPE",
  NAME_TOO_LONG: "NAME_TOO_LONG",
  PHONE_REQUIRED: "PHONE_REQUIRED",
  PHONE_INVALID: "PHONE_INVALID",
  PHONE_INVALID_TYPE: "PHONE_INVALID_TYPE",
  MESSAGE_TOO_LONG: "MESSAGE_TOO_LONG",
  CAPTCHA_REQUIRED: "CAPTCHA_REQUIRED",
  INVALID_CAPTCHA: "INVALID_CAPTCHA",
};